version: '3'

services:
  ui_dev:
    build:
      context: .
      dockerfile: apps/ui-react/Dockerfile
      args:
      - PORT=4000
      - NODE_ENV=development
    ports:
      - 4000:4000
    volumes:
      - ./:/usr/src/app
      - /usr/src/app/node_modules
      - /usr/src/app/apps/ui-react/node_modules
    command: pnpm run ui-react

  backend:
    build:
      context: apps/backend
      args:
        - PORT=4000
        - NODE_ENV=production
    ports:
      - 8000:4000
    command: pnpm start

  backend_dev:
    build:
      context: apps/backend
      args:
        - PORT=4000
        - NODE_ENV=development
    depends_on:
      - db
    ports:
      - 8000:4000
    env_file:
      - ./.env.development.local
    volumes:
      - ./apps/backend/:/usr/src/app
      - /usr/src/app/node_modules
    command: pnpm start:dev

  db:
    image: postgres
    restart: always
    ports:
      - '5432:5432'
    env_file:
      - ./.env.development.local
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
