version: '3'

services:
  backend:
    build:
      context: packages/backend
      args:
        - PORT=4000
    ports:
      - '8000:4000'
    environment:
      - NODE_ENV=production
    command: pnpm start

  backend_dev:
    build:
      context: packages/backend
      args:
        - PORT=4000
    ports:
      - '8000:4000'
    volumes:
      - ./packages/backend/:/usr/src/app
      - /usr/src/app/node_modules
    environment:
      - NODE_ENV=development
    command: pnpm start:dev
