version: '3'

services:
  ui_dev:
    build:
      context: .
      dockerfile: apps/ui-react/Dockerfile
      target: dev
      args:
      - PORT=4000
      - NODE_ENV=development
    ports:
      - 4000:4000
    volumes:
      - ./:/usr/src/app
      - /usr/src/app/node_modules
      - /usr/src/app/apps/ui-react/node_modules
    command: pnpm ui-react:dev

  api:
    build:
      context: .
      dockerfile: apps/api-express/Dockerfile
      target: prod
      args:
        - PORT=8000
        - NODE_ENV=production
    ports:
      - 8000:8000
    env_file:
      - ./.env

  api_dev:
    build:
      context: .
      dockerfile: apps/api-express/Dockerfile
      target: dev
      args:
        - PORT=8000
        - NODE_ENV=development
    depends_on:
      - db
    ports:
      - 8000:8000
    env_file:
      - ./.env
    volumes:
      - ./:/usr/src/app
      - /usr/src/app/node_modules
    command: pnpm run api:dev

  db:
    image: postgres:15.2-alpine
    restart: always
    ports:
      - 5432:5432
    hostname: test_host
    env_file:
      - ./.env
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
