version: '3'

services:
  backend:
    build:
      context: packages/backend
      args:
        - PORT=4000
        - NODE_ENV=production
    ports:
      - 8000:4000
    command: pnpm start

  backend_dev:
    build:
      context: packages/backend
      args:
        - PORT=4000
        - NODE_ENV=development
    depends_on:
      - db
    ports:
      - 8000:4000
    env_file:
      - ./.env.development.local
    volumes:
      - ./packages/backend/:/usr/src/app
      - /usr/src/app/node_modules
    command: pnpm start:dev

  db:
    image: postgres
    restart: always
    ports:
      - '5432:5432'
    env_file:
      - ./.env.development.local
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
