name: lint

on: [push]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    container:
      image: node:18.12.1-alpine
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
        name: Install pnpm
        with:
          version: 7
      - uses: actions/cache@v3
        name: Cache dependencies
        with:
          path: node_modules
          key: pnpm-${{ hashFiles('pnpm-lock.yaml') }}
          restore-keys: pnpm-
      - name: Install dependencies
        run: pnpm install

  eslint:
    needs: build
    name: ESLint
    runs-on: ubuntu-latest
    container:
      image: node:18.12.1-alpine
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
        name: Install pnpm
        with:
          version: 7
      - uses: actions/cache@v3
        name: Cache dependencies
        with:
          path: node_modules
          key: pnpm-${{ hashFiles('pnpm-lock.yaml') }}
          restore-keys: pnpm-
      - name: Lint source code with ESLint
        run: pnpm run lint

  prettier:
    needs: build
    name: Prettier
    runs-on: ubuntu-latest
    container:
      image: node:18.12.1-alpine
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
        name: Install pnpm
        with:
          version: 7
      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: node_modules
          key: pnpm-${{ hashFiles('pnpm-lock.yaml') }}
          restore-keys: pnpm-
      - name: Prettify our source code with Prettier
        run: pnpm run check:format
