name: lint

on: [push]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    container:
      image: node:18.12.1-alpine
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
        name: Install pnpm
        id: pnpm-install
        with:
          version: 7
          run_install: false
      - name: Get pnpm store directory
        id: pnpm-cache
        shell: bash
        run: |
          echo "STORE_PATH=$(/)" >> $GITHUB_OUTPUT
      - uses: actions/cache@v3
        name: Cache dependencies
        with:
          path: ${{ steps.pnpm-cache.outputs.STORE_PATH }}
          key: pnpm-${{ hashFiles('pnpm-lock.yaml') }}
          restore-keys: pnpm-
      - name: Install dependencies
        run: pnpm install

  # eslint:
  #   needs: build
  #   name: ESLint
  #   runs-on: ubuntu-latest
  #   container:
  #     image: node:18.12.1-alpine
  #   steps:
  #     - uses: actions/checkout@v3
  #     - name: Install pnpm
  #     - name: Cache dependencies
  #       uses: actions/cache@v3
  #       with:
  #         path: ${{ steps.pnpm-cache.outputs.STORE_PATH }}
  #         key: pnpm-${{ hashFiles('pnpm-lock.yaml') }}
  #         restore-keys: pnpm-
  #     - name: Lint source code with ESLint
  #       run: pnpm run lint

  # prettier:
  #   needs: build
  #   name: Prettier
  #   runs-on: ubuntu-latest
  #   container:
  #     image: node:18.12.1-alpine
  #   steps:
  #     - uses: actions/checkout@v3
  #     - name: Install pnpm
  #     - name: Cache dependencies
  #       uses: actions/cache@v3
  #       with:
  #         path: ${{ steps.pnpm-cache.outputs.STORE_PATH }}
  #         key: pnpm-${{ hashFiles('pnpm-lock.yaml') }}
  #         restore-keys: pnpm-
  #     - name: Prettify our source code with Prettier
  #       run: pnpm run check:format
