name: lint

on: [push]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    container:
      image: node:18.12.1-alpine
    steps:
      - uses: actions/checkout@v3
      - name: Install pnpm
        run: npm install --global pnpm@latest
      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: ~/.pnpm
          key: pnpm-${{ hashFiles('pnpm-lock.yaml') }}
          restore-keys: pnpm-
      - name: Install dependencies
        run: pnpm install --frozen-lockfile

  eslint:
    needs: build
    name: ESLint
    runs-on: ubuntu-latest
    container:
      image: node:18.12.1-alpine
    steps:
      - uses: actions/checkout@v3
      - name: Install pnpm
        run: npm install --global pnpm@latest
      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: ~/.pnpm
          key: pnpm-${{ hashFiles('pnpm-lock.yaml') }}
          restore-keys: pnpm-
      - name: Lint source code with ESLint
        run: pnpm run lint

  prettier:
    needs: build
    name: Prettier
    runs-on: ubuntu-latest
    container:
      image: node:18.12.1-alpine
    steps:
      - uses: actions/checkout@v3
      - name: Install pnpm
        run: npm install --global pnpm@latest
      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: ~/.pnpm
          key: pnpm-${{ hashFiles('pnpm-lock.yaml') }}
          restore-keys: pnpm-
      - name: Prettify our source code with Prettier
        run: pnpm run check:format
