name: lint

on: [push]

jobs:
  eslint:
    name: ESLint
    runs-on: ubuntu-latest
    container:
      image: node:18.12.1-alpine
    steps:
      - uses: actions/checkout@v3
      - name: Install pnpm
        run: npm install
      - name: Install dependencies
        run: pnpm install
      - name: Lint source code with ESLint
        run: pnpm run lint

  prettier:
    name: Prettier
    runs-on: ubuntu-latest
    container:
      image: node:18.12.1-alpine
    steps:
      - uses: actions/checkout@v3
      - name: Install pnpm
        run: npm install
      - name: Install dependencies
        run: pnpm install
      - name: Prettify our source code with Prettier
        run: pnpm run check:format
