name: lint

on: [push]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    container:
      image: node:18.12.1-alpine
    steps:
      - uses: actions/checkout@v3
      - name: Install pnpm
        run: npm install --global pnpm@latest
      - uses: actions/cache@v3
        name: Cache dependencies
        with:
          path: ~/.pmpm
          key: pnpm-${{ hashFiles('pnpm-lock.yaml') }}
          restore-keys: npm-
      - name: Install dependencies
        run: pnpm install --frozen-lockfile
      - name: Build
        run: npm run build
      - name: Archive build
        uses: actions/upload-artifact@v2
        with:
          name: build
          path: build

  eslint:
    needs: build
    name: ESLint
    runs-on: ubuntu-latest
    container:
      image: node:18.12.1-alpine
    steps:
      - name: Download a single artifact
        uses: actions/download-artifact@v2
        with:
          name: build
      - uses: actions/checkout@v3
      - uses: actions/cache@v3
        name: Cache dependencies
        with:
          path: ~/.pmpm
          key: pnpm-${{ hashFiles('pnpm-lock.yaml') }}
          restore-keys: npm-
      - name: Lint source code with ESLint
        run: pnpm run lint

  prettier:
    needs: build
    name: Prettier
    runs-on: ubuntu-latest
    container:
      image: node:18.12.1-alpine
    steps:
      - name: Download a single artifact
        uses: actions/download-artifact@v2
        with:
          name: build
      - uses: actions/checkout@v3
      - uses: actions/cache@v3
        name: Cache dependencies
        with:
          path: ~/.pmpm
          key: pnpm-${{ hashFiles('pnpm-lock.yaml') }}
          restore-keys: npm-
      - name: Prettify our source code with Prettier
        run: pnpm run check:format
